eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka_url:http://192.168.1.12:8761/eureka}
  instance:
    hostname: 192.168.1.12
    prefer-ip-address: true
